### ISSUE TITLE
Settings popup needs resized

### ISSUE THREAD

**Issue by Technetium1** [SmokeyLlama/JumpinLlama#25]
Settings popup is way too small, it can't show all the options anymore.

**Comment by Technetium1** [comment]
I feel a better solution for this would be forcing it fill the entire canvas.

**Comment by smokeyllama** [comment]
corrected in: https://github.com/SmokeyLlama/JumpinLlama/commit/0c7565dc8a05c0780b23af30658b093952e6350b

I didnt fill to fit, because thats how it is without the theme.
Instead I increased the width size. and themed the scrollbars to not take so much space.
